### PR TITLE
RLFL: A Reinforcement Learning Framework for Active Federated Learning

### PR DESCRIPTION
**Pull request by silviafeiwang**
This implements a reinforcement learning framework for learning and controlling federated learning tasks

## Description

The added directory `plato/utils/rlfl` is the framework base; the added directory `examples/fei` is an instance of a DRL agent  that learns the global aggregation strategy.

## How has this been tested?

Tests of the instance `examples/fei` are passed on the latest plato environment.

To know how to customize another DRL agent and run the training/testing, please refer to `plato/utils/rlfl/README.md`.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) Fixes #
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by silviafeiwang** [comment]
- [x] Cleaned and formatted the code
- [x] Added reference to some code
- [x] Moved documentation for RL to docs/
- [x] Moved .yml into the directory of the example
- [ ] Rename AFL to ActiveFL

> In their paper, they call the algorithm as AFL.

- [ ] Just call the `agent.start_agent()` function instead of using `asyncio.run()`

> I tried but failed. The agent functions like another base client and communicates with the server through socket.io. If just calling the function, the program will get stuck at the beginning as the server has trouble connecting all those clients as well as the agent.

- [ ] Add more details to the documentation and also the docstrings for the functions in policies/td3.py

**Comment by baochunli** [comment]
I ran `python examples/fei/fei.py -c examples/fei/fei_FMNIST_lenet5.yml`, and it was stuck after running for about 20 minutes:

```
[INFO][16:04:50]: [Server #14610] Sending the current state at episode 0 timestep 19 to RL Agent.
[INFO][16:04:50]: [Server #14610] Sent 505 B of update data to RL Agent.
[INFO][16:04:50]: [RL Agent] Updated by the server.
[INFO][16:04:50]: [RL Agent] Received 505 B of update data from the server.
[INFO][16:04:50]: [RL Agent] Episode #0 ended.
[INFO][16:04:50]: [RL Agent] Saving the experience into replay buffer.
[INFO][16:04:50]: [RL Agent] Updating the policy.
[INFO][16:04:50]: [RL Agent] Model saved to ./models/td3/iter0_.
[INFO][16:04:50]: [RL Agent] Reseting RL environment.
[INFO][16:04:50]: [RL Agent] Starting RL episode #1.
/Users/bli/Playground/plato/examples/fei/fei_agent.py:85: RuntimeWarning: coroutine 'AsyncClient.emit' was never awaited
  self.sio.emit('env_reset', {'current_episode': self.current_episode})
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by baochunli** [comment]
With respect to the concept of `RL_agent` (which appears to be a client to `RL_server`), I am not sure why it needs to be executed in a separate process. None of its code seems to be time-consuming and computationally intensive.

**Comment by baochunli** [comment]
With respect to the concept of `RL_server`, the current design is difficult for me to understand. It appears that the RL server replaces the traditional federated learning server, which takes care of the model aggregation process. This `RL_server` appears to be inheriting from `fedavg.Server` (line 58, `simple_rl_server.py`), but it copied and pasted a lot of code from `servers/base.py` which I don't see why. 

It is typically strongly discouraged to copy and paste code across the board, since otherwise the same code must be changed in multiple places when a change is needed. Copying and pasting code is also typically considered a telling sign for poor software design.

`RL_server` seems to be just a place for making DRL decisions and computing actions. I am not sure why this cannot be done by the RL agent. It is also not clear where the RL agent runs: is it physically on the client devices (say on an Android phone) or on the server? The current code is confusing at least based on what I can understand and read.

**Comment by silviafeiwang** [comment]
> With respect to the concept of `RL_agent` (which appears to be a client to `RL_server`), I am not sure why it needs to be executed in a separate process. None of its code seems to be time-consuming and computationally intensive.

I thought it's necessary to be executed in a separate process so the RL training and decision making on agent side can progress concurrently with the model updates between the FL server and clients. Like we did earlier in the program for RL-based congestion control, we tried to avoid the RL policy update blocking the packets transmission between the server and client.

**Comment by silviafeiwang** [comment]
> With respect to the concept of `RL_server`, the current design is difficult for me to understand. It appears that the RL server replaces the traditional federated learning server, which takes care of the model aggregation process. This `RL_server` appears to be inheriting from `fedavg.Server` (line 58, `simple_rl_server.py`), but it copied and pasted a lot of code from `servers/base.py` which I don't see why.
> 
> It is typically strongly discouraged to copy and paste code across the board, since otherwise the same code must be changed in multiple places when a change is needed. Copying and pasting code is also typically considered a telling sign for poor software design.
>
> `RL_server` seems to be just a place for making DRL decisions and computing actions. I am not sure why this cannot be done by the RL agent. It is also not clear where the RL agent runs: is it physically on the client devices (say on an Android phone) or on the server? The current code is confusing at least based on what I can understand and read.

You're right. The RL server replaces the traditional federated learning server and `RL_server` is inheriting from `fedavg.Server`. And to answer the last question, the RL agent runs on the server and takes control of the server. 

That's why I need to revise the loop and override some functions of the server. For example, the server previously `process_reports` (where model aggregation happens) once it receives all the updates from the selected clients. But now since it's the RL agent that makes decision on the model aggregation, the server has to wait for the agent's next action before it `process_reports`.

**Comment by silviafeiwang** [comment]
> I ran `python examples/fei/fei.py -c examples/fei/fei_FMNIST_lenet5.yml`, and it was stuck after running for about 20 minutes:
> 
> ```
> [INFO][16:04:50]: [Server #14610] Sending the current state at episode 0 timestep 19 to RL Agent.
> [INFO][16:04:50]: [Server #14610] Sent 505 B of update data to RL Agent.
> [INFO][16:04:50]: [RL Agent] Updated by the server.
> [INFO][16:04:50]: [RL Agent] Received 505 B of update data from the server.
> [INFO][16:04:50]: [RL Agent] Episode #0 ended.
> [INFO][16:04:50]: [RL Agent] Saving the experience into replay buffer.
> [INFO][16:04:50]: [RL Agent] Updating the policy.
> [INFO][16:04:50]: [RL Agent] Model saved to ./models/td3/iter0_.
> [INFO][16:04:50]: [RL Agent] Reseting RL environment.
> [INFO][16:04:50]: [RL Agent] Starting RL episode #1.
> /Users/bli/Playground/plato/examples/fei/fei_agent.py:85: RuntimeWarning: coroutine 'AsyncClient.emit' was never awaited
>   self.sio.emit('env_reset', {'current_episode': self.current_episode})
> RuntimeWarning: Enable tracemalloc to get the object allocation traceback
> ```

I didn't meet this error before modifying the `reset` method in `simple_rl_agent.py` (and `fei_agent.py`) to be non-asynchronous. The `reset` method was made async because line 75 in `simple_rl_agent.py` is async.

**Pull request merged**
