### PR TITLE
Adjusted default values for configurations

### PR DESCRIPTION
**Pull request by cying17**
This PR adjusted default values for configurations, based on Issue #171. 

## Description

This PR adjusted default values for configurations so that most configuration files can be shorter. New default values assume that a single server, with one or multiple GPUs, is used for most runs.

* Set the default value of `server.comm_simulation` to true.

* Added a new section `general` and a base path, `general.base_path`.
This `general` section is optional, and this base path is used as the prefix of directory of dataset, models, checkpoints, and results, i.e., `data.data_path`, `server.model_path`, `server.checkpoint_path`, and `results.result_path`.

* Revised the directories of dataset, models, checkpoints, and results.
For the consistency of naming, `model_dir`, `checkpoint_dir`, and `result_dir` are changed to `model_path`, `checkpoint_path`, and `result_path`, respectively.

* Supported a default `results` section.
Got rid of the need of explicitly specifying a `results` section in the configuration file to record results. We now have:
    - a default `results.result_path`, 
    - a default set of columns in the .csv file, i.e., `results.types`, which contains round number, global model accuracy, and elapsed training time
    - a default set of pairs to be plotted as .pdf files, i.e., `results.plot`, which contains round number vs. global model accuracy, and elapsed training time vs. global model accuracy.
   
* Changed the default value of `server.ping_timeout` to 3600.
Since in the current implementation, all of the launched client processes are used all the time in a FL training session, the value of ping_timeout doesn't have to be extremely large as the server will respond all of them in every communication round.
3600 seconds should be enough for most training sessions. It is enough for selecting 200 clients per round to train the ResNet-18 model.

## How has this been tested?

Tested with ./run -c configs/MNIST/fedavg_lenet5.yml
./run -c configs/MNIST/fedavg_cross_silo_lenet5.yml
and ./run -c configs/CIFAR10/fedavg_resnet18.yml

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) Fixes #
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by baochunli** [comment]
I think the default `data_path` should also be relative to `base_path`, i.e., `base_path/data` rather than `./data`.

Since `base_path` will be used for both the clients and the server, it can be in a new `general` section at the top of the configuration file.

Also, it would be great if we make the naming consistent, and call `model_dir`, `checkpoint_dir`, and `result_dir` `model_path`, `checkpoint_path`, and `result_path`, respectively.

The default path for checkpoints: perhaps it is better to make it `/checkpoints` rather than `/models/checkpoints`?

**Comment by baochunli** [comment]
It would be great if a default `results` section is supported, without the need of explicitly specifying this section. It should perhaps have a default `result_path`, and a default set of columns in the .csv file.

**Comment by baochunli** [comment]
Also, `general.base_path` should be optional — if it is not supplied, the default is the current directory `./`.

**Comment by cying17** [comment]
For the default data_path, because the default of base_path is `./<datasource>_<model>_<server_type>`, and I thought different models and servers may use the same dataset, so I set the default data_path to simply `./data`. But what you say about making the default of base_path as `./` makes more sense. I will change the default data_path to `<base_path>/data`.

Having a new general section at the top of the configuration file is a good idea. I will implement that and make the default as `./`.

Ok, I will change the naming to model_path, checkpoint_path, and result_path for consistency.

I will make the default path for checkpoints to `<base_path>/checkpoints`.

Sure, we will have a default results section. The default set of columns will be round, accuracy, and elapsed_time.

**Comment by baochunli** [comment]
Great!

**Pull request merged**
