### PR TITLE
Add new config file for FedAsync example to reproduce the experiment in the original paper

### PR DESCRIPTION
**Pull request by cuiboyuan**
Add new YML file for FedAsync example to reproduce the CIFAR10 experiment in the original paper
## Description

Add new file `fedasync_CIFAR10_resnet18.yml` under `examples/fedasync` that tries to reproduce the experiment with CIFAR10 dataset in the original FedAsync paper.

Also update `fedasync_server.py` to support the use of different staleness weighting functions mentioned in the paper when updating the mixing hyperparameter

## How has this been tested?

Execute the following command with no error:
`python run.py --config=examples/fedasync/fedasync_CIFAR10_resnet18.yml`

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) Fixes #
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

## Additional Context
1. The original paper uses its own custom convolutional neural network to run the experiments, which I'm not so sure how to reproduce in the Plato framework, so I just use the existing ResNet18 model.
2. The original paper also simulates the staleness of clients directly from a uniform distribution, so they can control the max staleness of clients, which I think is not possible to be entirely reproduced in the Plato framework. Thus, I just simulate the client's sleep time from a uniform distribution and set the `staleness_bound` correspondingly, which is not a 100% reproduction but similar to the design of the original paper

### CODE REVIEW

**Comment by cuiboyuan** [comment]
I also have a question about the FedAsync example. I noticed that the assignment of `os.environ['config_file']` is removed from both `fedasync.py` and `port.py`, so when the user directly runs these two python files, an error will be raised because no config file is provided, so the user is forced to use `run.py` script with the example's config file. Is this behavior intentional? That we don't want the users to run the examples using the python file under the `examples` directory?

Thanks!

**Comment by baochunli** [comment]
You can use any configuration file at the command line using the '-c' option. Example:

python examples/fedasync/fedasync.py -c examples/fedasync/feaasync_cifar10_resnet18.yml

**Comment by cuiboyuan** [comment]
> You can use any configuration file at the command line using the '-c' option. Example:
> 
> python examples/fedasync/fedasync.py -c examples/fedasync/fedasync_CIFAR10_resnet18.yml

I see. Thanks!

Also a question about the simulated client speed. I noticed that currently the client seems to have the same sleep time after each epoch. Is that a bug? Or is it intentional to remove the variance of sleep time at the end of each epoch?

**Comment by baochunli** [comment]
This is intentional to improve reproducibility, without which it is impossible to compare across algorithms across the board.

**Comment by cuiboyuan** [comment]
> This is intentional to improve reproducibility, without which it is impossible to compare across algorithms across the board.

I see. Thanks!

**Pull request merged**
