### PR TITLE
[FluentPS] Added sync controller for supporting BSP, SSP, and ASP.

### PR DESCRIPTION
**Pull request by XinYao1994**
## Description

BSP, SSP, ASP, etc, are widely used in traditional distributed deep learning systems. Previously, Plato has already supported BSP and ASP, while we need to model the synchronization process and provide a more flexible way to support various synchronization models. Motivated by FluentPS paper, we added a general programming model for synchronization. The lazy execution could help reduce the frequent synchronization, even in some weak synchronization models [1].

[1] X. Yao, X. Wu and C. -L. Wang, "FluentPS: A Parameter Server Design with Low-frequency Synchronization for Distributed Deep Learning," 2019 IEEE International Conference on Cluster Computing (CLUSTER), 2019, pp. 1-12, doi: 10.1109/CLUSTER.2019.8891038. 

## How has this been tested?

In this PR, we mainly added the staleness controller for synchronization and updated the codes in the base server.
The code is evaluated via the GitHub CI tests. Different from the previous configuration, we used ```synchronous_staleness``` to set the staleness threshold.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) Fixes #
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by baochunli** [comment]
This codebase is very difficult to understand (the paper more confusing than the code).

Starting from the very beginning, the current version of Plato already supports synchronous mode and asynchronous mode (with a `periodic_interval` for aggregating the model updates and selecting new clients to replace existing reported ones — see README.md for more details).

What is the precise definition of so-called "SSP" in the specific context of Plato and federated learning? How do you define staleness of the clients in this context? These are not clear, since if a client sent a model update to the server, there is no way that the server will not use it for aggregation. On the other hand, if a client waits for sending model updates, that would be equivalent to having its own "number of epoches" for each communication round, which is easy to implement but I am not sure what the motivation is.

In general, I found the whole notion of "SSP" in federated learning unclear.

**Comment by XinYao1994** [comment]
Many thanks for your time. 

## The issue of using ```periodic_interval```
It is usually very hard to determine an adaptive ```periodic_interval``` under federated learning because the clients in one round are heterogeneous and randomly chosen from a large number of clients. It is natural to use the progress to replace the timeout method.

## What is the precise definition of so-called "SSP" in the specific context of Plato and federated learning?
In current implementation, it regards the number of rounds (similar to the number of iterations) as the training progress. Therefore, the gap between the number of rounds of the fastest clients and that of the slowest clients cannot be larger than ```s``` iterations. 

## How do you define staleness of the clients in this context?
As mentioned before, staleness is defined as the progress gap between the fastest clients and the fastest slowest. The definition of the progress of a client is defined as follows: 
1. The server only maintain k progress records (k is the number of selected clients in each round)
2. Progress starts from 1
3. When the server receives the model update from a client, it will increase 1 on this client's progress records.
4. Since the client in step 3 has finished the model update, the server needs to select a new client, and the updated progress record (+1 in step 3) will be binding with the new selected client.

## These are not clear, since if a client sent a model update to the server, there is no way that the server will not use it for aggregation.
In [previously implementation](https://github.com/XinYao1994/FluentPS-paper.git), the server will immediately update the model update when receiving it. 
However, in federated learning, it is usually hard to know the weights until receiving all updates or several updates. Therefore, current implementation uses ```k``` as the buffered updates, i.e., only after receiving k updates, it can calculate k weights and do the aggregation.

## On the other hand, if a client waits for sending model updates, that would be equivalent to having its own "number of epoches" for each communication round, which is easy to implement but I am not sure what the motivation is.
It is not recommended to use ```wait``` at sending (push) phase. The sending should be unblocked since the server hopes to receive as many updates as possible. In our framework (paper), ```wait``` only happens at the pull phase. Because some slow clients are not pushing their updates, other clients need to wait for it to finish that before they read the updated models (pulling the model from servers, or server sending the updated model to the clients).
In current implementation, the server will start its select_client only when the global model is updated enough.

If you have more confusing issues with the code or paper, it is welcome to talk to me and we can work together to fix them. Many thanks.

**Comment by baochunli** [comment]
I still fail to understand what this new algorithm is supposed to do. For example, when a client finishes local training and sends a model update to the server, what should the server do?

**Comment by XinYao1994** [comment]
## SSP
SSP (Stale Synchronous Parallel) is a widely used algorithm in traditional distributed machine learning systems. Different from Asynchronous Synchronous Parallel, it has theoretical proof to show Stale Synchronous Parallel can guarantee model convergence.

## The core idea of SSP
It allows weak synchronization among clients in a single round, while bounding the staleness.
When the progress gap between the fastest client and the slowest client is more than a given staleness threshold, the fast client (will read stale parameter from the server) will be paused by the server and wait for the model updates from the slow clients.

## The workflow 
when a client c(i) finishes local training and sends the model update to the servers.
1. the server first buffers the updates (need k updates for k weights) and inc 1 on the progress records.
2. if achieving k updates, execute aggregation
3. Since the progress records are updated, the server will check in the buffered pull requests (from fast clients). If the global is updated enough for these fast clients, the server will run select_client (not for c(i)) to dispatch the global model to newly selected clients.
4. the server will judge whether the global model is updated enough for c(i): if yes, it will run select_client to select a new client; if not, it will buffer this request as a buffered pull request and let it wait until the global model is updated enough.

**Comment by baochunli** [comment]
I understand what "SSP" was in its original context of parameter servers (represented by its 2013 paper), but what this term is supposed to mean in the specific context of federated learning remains unclear. I am also not a fan of reusing a term when it is applied to a new — and substantially different — context.

Here is my interpretation of what I can understand so far. Assuming that a federated learning session involves a total of 100 clients, with 3 clients selected in the initial communication round. Also assume that *staleness* is 2.

When a server sends out a model to a newly selected client, it will:

(1) Record the current communication round index for this client, indicating that this client is currently working in this communication round.

(2) Send out the current model.

When a server received a model update from a client it has previously selected, it will:

(1) "save" the model update for this reporting client; 

(2) If the slowest client is at least working in round #(current communication round index - 2), aggregate all the model updates received so far, and then select a new client to replace this reporting client and send out the newly aggregated model to the new client;

(3) Otherwise, do nothing.

Is this understanding correct?

**Comment by XinYao1994** [comment]
Pervious description is almost there:

## When a server sends out a model to a newly selected client
(1) 
a. if it is the initial round, the server records 0 for k round indexes and randomly selects k clients in the 1st round.
b. if k<sub>sub</sub> clients have reported, the server needs to randomly select k<sub>sub</sub> clients from unselected clients. The newly selected client will inherit the record from the reported client (by +1).
```python
client_id = selected_client_id
# client_id is the newly selected client and the reporting_clients[i] is the reported client.
client_progress[client_id] = self.staleness.clientprogress[self.reporting_clients[i]] + 1
```
(2) Send out the current model.

## When a server received a model update from a client (c[i]) it has previously selected
In fact, we only try to delay the fast clients and let them wait for the updates from the slow clients. 
That is to say, some reported client is too fast, and the server cannot directly run ```select_clients``` to replace these reported clients with newly selected clients. Before the model is enough new, the server needs to buffer them and wait (called delayed pull request).

(1) "save" the model update for this reporting client;

(1.5) If there are k buffered model updates, do aggregation. (stored in ```self.updates```)

(2) push condition: this condition is to judge whether this update (from c[i]) could make the global model enough new for sending the new model to newly selected clients. They are used to replace the fast-reported clients (in waiting state, they reported earlier than c[i]). 

a. if yes, run ```select_client``` and replace these reported clients with newly selected clients.
b. otherwise, do nothing.

(3) pull condition: this condition is to judge whether the server should select a new client to replace c[i].

a. if the server found c[i]'s progress is too advanced, the server regards it as a delayed pull request and buffers it.
b. otherwise, run ```select_client``` and replace c[i] with a newly selected client.

**Pull request closed without merging**
