### PR TITLE
Fixed the reported bug of the config test in #190

### PR DESCRIPTION
**Pull request by CSJDeveloper**
Noticing the bug reported in #190, I then fixed all issues that existed in the `tests/config_tests.py`. 

## Description

I made three changes to the code. First, I moved the configuration files, including Pipelines and Models, into the Kinetics directory. This fixed the issue of "FileNotFoundError". Second, all PyLint errors were addressed, making the code rate 10.00/10. Finally, I added more comments further to describe the objective of each unit test function.

## How has this been tested?

1. config_tests
As for the code running, I tested it with `python tests/config_tests.py`.
As for the format test, I executed the command `pylint tests/config_tests.py`.

2. data_tests
As for the code running, I tested it with `python tests/data_tests.py`.
As for the format test, I executed the command `pylint tests/data_tests.py`.

3. sampler_tests
As for the code running, I tested it with `python tests/sampler_tests.py`.
As for the format test, I executed the command `pylint tests/sampler_tests.py`.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue) Fixes #
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by baochunli** [comment]
Same error:

```
FileNotFoundError: [Errno 2] No such file or directory: '/home/bli/plato/configs/Kinetics/Models/kinetics_full_models.yml'
```

**Comment by CSJDeveloper** [comment]
Fixed all issues. Please access the "How has this been tested?" section above to test the code.

**Comment by baochunli** [comment]
I tried to fix as many PyLint errors as possible in `datasources/multimodal_base.py`, but the following errors still need attention:

```
multimodal_base.py:248:4: W0221: Number of parameters was 1 in 'DataSource.get_train_set' and is now 2 in overridden 'MultiModalDataSource.get_train_set' method (arguments-differ)
multimodal_base.py:254:4: W0221: Number of parameters was 1 in 'DataSource.get_test_set' and is now 2 in overridden 'MultiModalDataSource.get_test_set' method (arguments-differ)
```

**Comment by CSJDeveloper** [comment]
> I tried to fix as many PyLint errors as possible in `datasources/multimodal_base.py`, but the following errors still need attention:
> 
> ```
> multimodal_base.py:248:4: W0221: Number of parameters was 1 in 'DataSource.get_train_set' and is now 2 in overridden 'MultiModalDataSource.get_train_set' method (arguments-differ)
> multimodal_base.py:254:4: W0221: Number of parameters was 1 in 'DataSource.get_test_set' and is now 2 in overridden 'MultiModalDataSource.get_test_set' method (arguments-differ)
> ```

I noticed that there are also other pylint errors. I will stop my current work to fix these issues.

**Comment by baochunli** [comment]
I am still waiting for follow up work in this PR.

**Pull request merged**
