### PR TITLE
Enable Oort working in the async mode.

### PR DESCRIPTION
**Pull request by Yufei-Kang**
## Description
Previously, the implementation of Oort cannot work normally in asynchronous mode since the server updates client utility according to the 'self.explored_client' list which contains delayed clients that haven't sent out the updates. To address it, we make the server update based on the update list.

## How has this been tested?
Ran 'oort_MNIST_lenet5.yml' in asynchronous environment.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue) Fixes #
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kevinsun203** [comment]
I think that before, it would select clients randomly and oort's selections wouldn't actually be trained. I changed it so that oort would select the number of clients needed (len(reported_clients) or len(current_processed_clients).

**Comment by Yufei-Kang** [comment]
> I think that before, it would select clients randomly and oort's selections wouldn't actually be trained. I changed it so that oort would select the number of clients needed (len(reported_clients) or len(current_processed_clients).

Hi Kevin, thank you so much for your work. I ran the last version and found out that in async mode, server selects # 'server: minimum_clients_aggregated' rather than # 'Clients: per_round'. It can be reproduced by setting these two with different values. Could you please take a look at it at your convenience? Many thanks.

**Comment by kevinsun203** [comment]
Hi Yufei, sorry if I'm misinterpreting, but in async mode, I thought that the intention was to have: # of clients selected = # of clients who reported back (aggregated). I ran `./run -c examples/oort/oort_MNIST_lenet5.yml` in the main directory and it gave this output, so I thought that that was the intended behaviour: 
image

Sorry if I've misunderstood something.

**Comment by Yufei-Kang** [comment]
Hi Kevin, in async mode, to alleviate the negative impact of stragglers, the server is allowed to do aggregation before it receives all reports from the selected clients as long as # of report is greater than 'minimum_clients_aggregated'.  Usually, # of clients selected is greater than # of clients aggregated. When they are equal, federated learning runs in **sync** mode.

**Comment by kevinsun203** [comment]
Hi Yufei, with running the last config file on oort.py and run.py (random selection), I got the following outputs. Is that more like the desired behaviour?
[runasync.txt](https://github.com/TL-System/plato/files/9033142/runasync.txt)
[oortasync.txt](https://github.com/TL-System/plato/files/9033143/oortasync.txt)

**Comment by Yufei-Kang** [comment]
Hi Kevin, it's now. Many thanks for your hard work! : )

**Comment by cying17** [comment]
PR #225 solved this issue.

**Pull request closed without merging**
