### PR TITLE
Split learning update

### PR DESCRIPTION
**Pull request by wykjLDF**
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue) Fixes #
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by baochunli** [comment]
The run will lead to an error when client #2 arrives before client #1:

[Server #11782] Starting round 1/6.
[ERROR][15:23:12]: Task exception was never retrieved
future: <Task finished name='Task-40' coro=<AsyncServer._handle_event_internal() done, defined at /usr/local/miniconda/envs/federated/lib/python3.8/site-packages/socketio/asyncio_server.py:502> exception=KeyError(1)>
Traceback (most recent call last):
  File "/usr/local/miniconda/envs/federated/lib/python3.8/site-packages/socketio/asyncio_server.py", line 504, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/usr/local/miniconda/envs/federated/lib/python3.8/site-packages/socketio/asyncio_server.py", line 540, in _trigger_event
    return await self.namespace_handlers[namespace].trigger_event(
  File "/usr/local/miniconda/envs/federated/lib/python3.8/site-packages/socketio/asyncio_namespace.py", line 37, in trigger_event
    ret = await handler(*args)
  File "/usr/local/miniconda/envs/federated/lib/python3.8/site-packages/plato/servers/base.py", line 38, in on_client_alive
    await self.plato_server.register_client(sid, data['id'])
  File "/usr/local/miniconda/envs/federated/lib/python3.8/site-packages/plato/servers/base.py", line 133, in register_client
    await self.select_clients()
  File "/usr/local/miniconda/envs/federated/lib/python3.8/site-packages/plato/servers/base.py", line 206, in select_clients
    sid = self.clients[client_id]['sid']
KeyError: 1
[INFO][15:23:12]: [Server #11782] New client with id #1 arrived.
[INFO][15:23:12]: [Server #11782] New client with id #3 arrived.

**Comment by baochunli** [comment]
Lots of unused variables in split_learning_algorithm.py. For example, in line 108-128, I suggest removing unused variables by changing to:

        tic = time.perf_counter()

        # Initializing the optimizer
        get_optimizer = getattr(self, "get_optimizer",
                                optimizers.get_optimizer)
        optimizer = get_optimizer(self.model)

        grad_index = 0

        for __, (examples, __) in enumerate(data_loader):
            optimizer.zero_grad()
            outputs = self.model.forward_to(examples, cut_layer)
            outputs.backward(self.gradients_list[grad_index])
            grad_index = grad_index + 1
            optimizer.step()

        toc = time.perf_counter()

        logging.info("[Client #%d] Training completed.", self.client_id)
        logging.info("[Client #{}] Time used: {:.2f} seconds.".format(
            self.client_id, toc - tic))

**Comment by baochunli** [comment]
Lots of commented out code in split_learning_server.py. These need to be cleaned up.

**Comment by wykjLDF** [comment]
The bugs have been fixed, please oblige me with your valuable comments!

**Comment by baochunli** [comment]
I have pushed some minor code cleanup. However, the client doesn't start with the current version correctly. The server simply waits for the client forever. Please test again.

**Comment by wykjLDF** [comment]
Got it, I will check it as soon. Thanks a lot!

**Pull request merged**
